/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "key_values_constants.h"

namespace key_value_database {

const key_valuesConstants g_key_values_constants;

key_valuesConstants::key_valuesConstants() {
}

} // namespace

