/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef key_values_CONSTANTS_H
#define key_values_CONSTANTS_H

#include "key_values_types.h"

namespace key_value_database {

class key_valuesConstants {
 public:
  key_valuesConstants();

};

extern const key_valuesConstants g_key_values_constants;

} // namespace

#endif
