// This autogenerated skeleton file illustrates how to build a server.
// You should copy it to another filename to avoid overwriting it.

#include "Key_Value_Database_Service.h"
#include <thrift/protocol/TBinaryProtocol.h>
#include <thrift/server/TSimpleServer.h>
#include <thrift/transport/TServerSocket.h>
#include <thrift/transport/TBufferTransports.h>

using namespace ::apache::thrift;
using namespace ::apache::thrift::protocol;
using namespace ::apache::thrift::transport;
using namespace ::apache::thrift::server;

using boost::shared_ptr;

using namespace  ::key_value_database;

class Key_Value_Database_ServiceHandler : virtual public Key_Value_Database_ServiceIf {
 public:
  Key_Value_Database_ServiceHandler() {
    // Your initialization goes here
  }

  void get(Person& _return, const int32_t key) {
    // Your implementation goes here
    printf("get\n");
  }

  void put(const int32_t key, const Person& value) {
    // Your implementation goes here
    printf("put\n");
  }

  void list_values(std::vector<Person> & _return) {
    // Your implementation goes here
    printf("list_values\n");
  }

  void delete_value(const int32_t key) {
    // Your implementation goes here
    printf("delete_value\n");
  }

};

int main(int argc, char **argv) {
  int port = 9090;
  shared_ptr<Key_Value_Database_ServiceHandler> handler(new Key_Value_Database_ServiceHandler());
  shared_ptr<TProcessor> processor(new Key_Value_Database_ServiceProcessor(handler));
  shared_ptr<TServerTransport> serverTransport(new TServerSocket(port));
  shared_ptr<TTransportFactory> transportFactory(new TBufferedTransportFactory());
  shared_ptr<TProtocolFactory> protocolFactory(new TBinaryProtocolFactory());

  TSimpleServer server(processor, serverTransport, transportFactory, protocolFactory);
  server.serve();
  return 0;
}

