/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

public enum City
{
  GUAYAQUIL = 1,
  QUITO = 2,
  CUENCA = 3,
  AMBATO = 4,
}
